### ISSUE TITLE
Collab won't generate zips when source is a YouTube video with a long filename

### ISSUE THREAD

**Issue by YossiMH** [oxai/deepsaber#5]
Reproducable by passing https://www.youtube.com/watch?v=_a0PscfuhGo into the collab.

**Comment by guillefix** [comment]
I guess a fix for this could be to just truncate the name before generating the zip. Will try to do that later

**Comment by sn0opy** [comment]
> I guess a fix for this could be to just truncate the name before generating the zip. Will try to do that later

Any ETA on that? The problem still persists.

**Comment by guillefix** [comment]
this is fixed in the last version of the colab. 
e.g. generated https://skystudioapps.com/bs-viewer/?url=https://docs.google.com/uc?export=download&id=1GFVCSfRIAeRK_eMB8RMkKtbx_5g8Cocv
